set -g mode-style "fg=#CDD6F5,bg=#073642"

set -g message-style "fg=#CDD6F5,bg=#073642"
set -g message-command-style "fg=#CDD6F5,bg=#073642"

set -g pane-border-style "fg=#073642"
set -g pane-active-border-style "fg=#CDD6F5"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#586e75,bg=#0E0F10"

set -g status-bg "#0E0F10"

set -g status-left-length "100"
set -g status-right-length "200"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-interval 15
WEATHER='#(curl -s wttr.in/CLT\?u\&format\="%%c%%20%%t%%20%%w&period=60")'
# WEATHER=''
MUSIC="#( ~/.config/scripts/ytmd_status.sh ) "

set -g status-left "#[fg=#073642,bg=#CDD6F5,nobold] #S #[fg=#CDD6F5,bg=#0E0F10,nobold,nounderscore,noitalics]"
# #[fg=#15161E,bg=#93a1a1,bold] #(whoami) #[fg=#93a1a1,bg=#0E0F10]

set -g status-right "#[fg=#CBA6F8,bg=#0E0F10,nobold,nounderscore,noitalics]#{?client_prefix,#[reverse] ┣━#[noreverse],}#[fg=#0E0F10,bg=#0E0F10,nobold,nounderscore,noitalics]#[fg=#CBA6F8,bg=#0E0F10] $MUSIC $WEATHER #[fg=#6f00bf,bg=#0E0F10]#[fg=#CDD6F5,bg=#6f00bf] %a, %b %d %l:%M %p "

setw -g window-status-activity-style "underscore,fg=#6f00bf,bg=#CDD6F5"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#0E0F10,bg=#CBA6F8"
setw -g window-status-format '#[fg=#0E0F10,bg=#CBA6F8]#[default] #I  #W #[fg=#CBA6F8,bg=#0E0F10,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=#0E0F10,bg=#CDD6F5]#[fg=#0E0F10,bg=#CDD6F5] #I #[fg=#CDD6F5,bg=#6f00bf]#[fg=#CDD6F5,bg=#6f00bf] #W #[fg=#6f00bf,bg=#0E0F10,nobold]'

# colors from cobalt2
#############################
# darker = "#0E0F10",
# gray = "#313244",
# blue = "#89B4FB"
# purple = "#6f00bf",
# light purple = "#CBA6F8"
# white = "#CDD6F5"

# arrows
#############################
#     

# Tmux Vars
#############################

# $(echo $USER) - shows the current username
# %a --> Day of week (Mon)
# %A --> Day of week Expanded (Monday)

# %b --> Month (Jan)
# %d --> Day (31)
# %Y --> Year (2017)

# %D --> Month/Day/Year (12/31/2017)
# %v --> Day-Month-Year (31-Dec-2017)

# %r --> Hour:Min:Sec AM/PM (12:30:27 PM)
# %T --> 24 Hour:Min:Sec (16:30:27)
# %X --> Hour:Min:Sec (12:30:27)
# %R --> 24 Hour:Min (16:30)
# %H --> 24 Hour (16)
# %l --> Hour (12)
# %M --> Mins (30)
# %S --> Seconds (09)
# %p --> AM/PM (AM)

# For a more complete list view: https://linux.die.net/man/3/strftime

#colour0 (black)
#colour1 (red)
#colour2 (green)
#colour3 (yellow)
#colour4 (blue)
#colour7 (white)
#colour5 colour6 colour7 colour8 colour9 colour10 colour11 colour12 colour13 colour14 colour15 colour16 colour17

#D ()
#F ()
#H (hostname)
#I (window index)
#P (current pane index)
#S (session index)
#T (pane title)
#W (current task like vim if editing a file in vim or zsh if running zsh)

