name: configs
root: ~/

windows:
  - zsh-config:
      panes:
        - vim:
            - sleep 0.5
            - cd ~/.config/
            - vim
  - tmux-config:
      panes:
        - vim:
            - cd ~/.config/tmux
            - vim
  - nvim-config:
      panes:
        - vim:
            - cd ~/.config/nvim
            - vim
# Run the script to execute commands after session is set up
# pre_window: ~/.config/tmuxinator/scripts/start-configs.sh
